import { ReactNode } from "react";
import { HeadComponent } from "./head-component";
import React from "react";

interface PageLayoutProps {
  children: ReactNode;
  title?: string;
  description?: string;
}

export const PageLayout: React.FC<PageLayoutProps> = ({
  children,
  title = "RainbowKit App",
  description = "Generated by @rainbow-me/create-rainbowkit",
}) => {
  return (
    <>
      <HeadComponent title={title} description={description} />
      <main className="min-h-[100vh] p-8 flex flex-col justify-center items-center gap-8">
        {children}
      </main>
    </>
  );
};
